name: Publish to PyPi


on:
  push:
    tags:
      - '*.*.*'

permissions: read-all

jobs:
  publish_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.12
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd # v3.0.1
        with:
          poetry-version: 2.1.3
      - name: Publish catalystwan
        run: |
          poetry config pypi-token.pypi ${{ secrets.CATALYSTWAN_PYPI_TOKEN }}
          poetry publish --build